### ISSUE TITLE
PRACTICA 4

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-s-b-j#2]
[REPORTE DE PRACTICA DEL MODELO DE  NEGOCIOS.pdf](https://github.com/user-attachments/files/17134710/REPORTE.DE.PRACTICA.DEL.MODELO.DE.NEGOCIOS.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Hola, buenos días compañero, excelente trabajo, 20% de 20% en base a la rúbrica .

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
